.gitignore
docs/api-reference/bird-management.md

Bash and Python examples added to "Reboot" section of Bird Management.
Scripts folder for testing of python scripts added to .gitignore

Bird Management Reboot examples and gitignore

---

docs/bird-management/notes.md
docs/console/licenses.md

- Refactor Bird Notes
- Add Console License Examples

Bird Notes and Console License Examples

---

docs/console/audit-trail.md
resources/sanitise.py

Minor changes were also made to the Audit Trail examples

Add sanitise.py script to resources folder

---

docs/canarytokens/actions.md
docs/canarytokens/clonedweb-ignorelist.md
docs/canarytokens/factory.md
docs/canarytokens/queries.md
resources/sanitise.py

Sanitise key list has also been updated

Add examples to CanaryTokens endpoints

---

docs/console-settings/api.md
docs/console-settings/canarytokens.md
docs/console-settings/ignore-lists.md
docs/console-settings/notification-channels.md
docs/console-settings/notification-settings.md
docs/console/global-search.md
docs/console/testing.md

Also adds examples to the Console - Global Search and Testing endpoints

Add examples to Console Settings endpoints

---

docs/console-settings/notification-channels.md

I think you should accept this

Add pubsub api endpoints

---

docs/bird-management/queries.md

Add /device/ips documentation

---

README.md
docs/flocks-settings/default-ignore-list.md

Include README correction that the docs site is live.

Remove // typos in URLs

---

docs/.vuepress/config.js
docs/canarytokens/googledocs.md
docs/canarytokens/office365.md

This is the final documentation for the more complicated Canarytokens.

Add documentation for office365 and googledocs

---

docs/common-tasks/incidents.md
docs/incidents/actions.md

-  Ran locally and visual inspection

Update HTTP POST to DELETE on '/incidents/delete'

---

docs/canarytokens/actions.md
docs/incidents/incident-objects.md

Updated some fields and fixed some grammatical errors.

Updated canarytokens/actions and incident-objects

---

docs/canarytokens/actions.md

This endpoints method only expects GET requests.

Update tokens list curl to GET

---

docs/console/audit-trail.md

Give explanations for the new parameters added to audit_trail/fetch

Add audit search params

---

docs/users/management.md

the curl and python are correct but the documented endpoint was wrong. 
Fixed and tested locally.

Fix globally enforce 2fa documented endpoint.

---

docs/canarytokens/office365.md

Add the API portion of O365 token custom 'from' address to docs

O365 sender field

---

docs/incidents/incident-objects.md

Adds the WinRM and RDP incident types, and re-alphabetizes the list

Add missing logtypes

---

docs/bird-management/personalities.md

Updated the endpoint with additional paramaters.

Update personalities list endpoint params

---

docs/console/testing.md

Update the documentation to reflect the correct POST method

Update the documentation to reflect the correct POST method

---

docs/console-settings/api.md

Update the global api add endpoint

---

docs/console-settings/api.md

Update documentation for missing parameter

---

docs/.vuepress/components/APIDetails.vue
docs/.vuepress/components/APIEndpoints.vue
docs/console-settings/api.md
docs/guide/getting-started.md

https://user-images.githubusercontent.com/89250089/231986333-14263997-e367-4f25-b1b8-8cce7d9688d5.mov

Add list endpoint for global api keys and update layout to show deprecated endpoints

---

docs/canarytokens/actions.md

This is an existing endpoint that was just missing from the docs.

Add the missing tokens fetch endpoint

---

docs/console-settings/notification-channels.md
docs/flocks-settings/webhooks.md

Update docs with info adding headers to generic webhooks

---

docs/.vuepress/config.js
docs/incidents/incident-objects.md
docs/syslog/rfc5424.md

Changes to Index
- Added Syslog examples
Changes to Incident Objects
- Added Canary Settings Changed
- Added Console Settings Changed
- Corrected spelling
- Added Dummy Incident
- Added HTTP API Request
- Tweaked alert headers
- Added LDAP Bind Attempt
- Added Local tampering Detected
Changes to syslog
- Added Canary Settings Changed
- Added Console Settings Changed
- Added Dummy Incident
- Added HTTP API Request
- Reordered HTTP Alerts (Alphabetical)
- Added Local Tampering Detected
- Added LDAP Bind Attempt
- Added MARK Message
- Trimmed SSH Key for viewing
- Fixed spacing on TFTP incident
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug be sure to link to that issue.
If it resolves a feature …

Added missing alert types and fixes

---

docs/canarytokens/actions.md

Add docs for Canarytoken redirect URL edit route.

Add docs for Canarytoken redirect URL edit route

---

docs/canarytokens/actions.md

Add docs for bulk Canarytoken delete endpoint.

Add docs for bulk Canarytoken delete endpoint

---

docs/bird-management/queries.md
docs/incidents/incident-objects.md

Proposed changes
Added missing API incident objects.
HTTP_POST = 3002
HTTP_ERROR = 3003
SSH_NEW_CONNECTION = 4000
SSH_REMOTE_VERSION_SENT = 4001
SMB_LOGIN = 5010
SMB_GROUP_ENUM = 5013
SMB_SHARE_CONNECT = 5014
PORT_SYN = 5001
PORT_SCAN_NET = 5002
PORT_RUNFINGER_SCAN = 5009
PORT_RUNFINGER_DIALECT = 5011
PORT_RUNFINGER_LANMAN = 5012
RDP_NEW_CONNECTION = 14001
RDP_FAILED_CONNECTION = 14002
RDP_LOGIN_ATTEMPT = 14004
TOKENS_DNS_DESKTOPINI = 16006
TOKENS_DNS_DOC_MSWORD = 16007
TOKENS_DNS_PDF_ACROBAT_READER = 16008
TOKENS_DNS_MSWORD_MACRO = 16009
TOKENS_DNS_MSEXCEL_MACRO = 16010
TOKENS_DNS_SENSITIVE_CMD = 16011
TOKENS_HTTP_REMOTE_IMAGE = 17001
TOKENS_HTTP_DOC_MSWORD = 17002
TOKENS_HTTP_CLONED_SITE = 17003
TOKENS_HTTP_AWS_S3 = 17005
TOKENS_HTTP_GOOGLE_DOCS = 17006
TOKENS_HTTP_GOOGLE_SHEETS = 17007 …

G updated incidents

---

docs/console/licenses.md

Remove reference to an old endpoint we deleted in February 2024.
N/A

Remove stale bird license endpoint from docs

---

docs/.vuepress/config.js
docs/breadcrumbs/mass-deployment.md
docs/breadcrumbs/overview.md

Adds API docs for the Breadcrumb endpoints, in order to promote their API use to customers.
N/A

Add Breadcrumb API docs

---

docs/.vuepress/styles/dark.styl

Add dark mode support for API doc tables.
- [] Documentation Update

Add dark mode styling for tables

---

docs/canarytokens/factory.md

Add documentation for css-token

Add doc entry for css token

---

docs/canarytokens/actions.md

Fix a broken link in the Canarytokens Actions page.

Update link to list kinds of canarytokens

---

docs/canarytokens/actions.md

Update the canarytoken create + S3 token remove docs, for AWS temp cred support.

Update canarytoken create docs for AWS temp cred support

---

docs/console-settings/canarytokens.md

Adds the new endpoint for listing a Console's user domains to the docs.

Add docs for listing user domains endpoint

---

docs/incidents/incident-objects.md

Add an incident object for File Share Login incident objects.

Add file share login incident object

---

docs/canarytokens/actions.md
docs/canarytokens/factory.md
docs/incidents/incident-objects.md

This changes adds some of the missing documentation from recent development.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Add missing features to docs

---

docs/canarytokens/factory.md

Removes a duplicate parameter `web_image` from the docs.
- [x ] Documentation Update

Remove duplicate web_image parameter

---

docs/canarytokens/office365.md

Updates docs to align with the edits made to the Office365 API endpoints.

Update Office365 mail token API docs

---

docs/bird-management/service-configuration.md

A small change that points to our KB article so users looking to push settings objects receive some guidance.

Add link to KB article for certificate and key for HTTPS
