thinkst/canarytools-docs

docs/flocks-settings/default-ignore-list.md
Clarify that the response includes a list globally ignored ports in
addition to IPs.
=> Update Flock sanitized ignore list endpoint

docs/canarytokens/actions.md
The docs incorrectly listed that parameter as optional.
Included minor word adjustments to make it easier to grasp the meaning
two Canarytoken endpoints.
=> Require the canarytoken param for fetch endpoint

docs/incidents/incident-objects.md, docs/syslog/rfc5424.md
In the previous incarnation of the Console documentation, this page laid
out the Syslog message format. This is an initial port of that content
to make it publicly available again.
=> Port Syslog RFC5424 format page to new docs site

docs/bird-management/outside-birds.md
Output for incidents/outside_bird/delete was updated to show number of source IPs making up deleted incidents
=> Outsidebird incident delete count

docs/flocks-settings/info.md, docs/flocks-settings/webhooks.md
Flocks can now have their own Splunk Webhook configured. This documents the APIs to add, test and remove this.
=> Document Splunk Flock Config API

docs/console-settings/notification-settings.md, docs/flocks-settings/notifications.md
Update the API for saving SMS numbers and email address notifications
allowing the field to be cleared, for flock and global settings.
=> Update the API for saving SMS and email notifications

docs/canarytokens/actions.md
Explains the clear_incidents parameter for canarytoken deletion, and clarifies that all incidents must be deleted to delete a token.
=> Add explanation of clear_incidents

docs/canarytokens/actions.md
The log bucket and source bucket to monitor *must* be specified to make a token. The API will block requests which do not specify them.
=> S3 tokens require source and log bucket to be specified

docs/flocks-settings/notifications.md
STR:
- go to https://docs.canary.tools/flocks-settings/notifications.html
- click on webhook url
goes to https://docs.canary.tools/flock-settings/webhooks.html and returns error
correct url is - https://docs.canary.tools/flocks-settings/webhooks.html
this PR fixes that
=> Fix 404 in notifications.md

docs/flocks-settings/webhooks.md
STR:
- go to https://docs.canary.tools/flocks-settings/webhooks.html#slack-webhooks
- click on ''here''
goes to https://help.canary.tools/help/edit-delete-how-do-i-webhook-notifications and returns 404
seems this is the correct url - https://help.canary.tools/hc/en-gb/articles/360012819778-How-do-I-configure-Slack-Webhook-notifications-
this PR fixes that
=> Fix 404 in webhooks.md

docs/canarytokens/factory.md
New required flock_id when creating a token factory auth string
Updated default message for the flock_id when creating a token using the factory
=> Mark the flock_id as required for when a factory is created

docs/console-settings/ignore-lists.md
Docs only mentioned Palo Alto's scanning of PDF tokens, so this updates that section to also mention Microsoft Defender as an annotation to use.
=> Update ignored annotations to mention Microsoft Defender

docs/canarytokens/actions.md, docs/canarytokens/queries.md
1. Update `docs/canarytokens/actions.md` to list the `/canarytokens/paginate` endpoint instead of the `/canarytokens/fetch` endpoint (it's still in `docs/canarytokens/queries.md`).
2. Update the description of the `search_string` parameter on the `/canarytokens/search` endpoint to clarify the way the search string is used.
=> Update `/canarytokens/fetch` and `/canarytokens/search`

docs/console/audit-trail.md
Add the missing `after_id` parameter to the `audit_trail/fetch` endpoint docs.
=> Add after_id to audit trail fetch

docs/bird-management/service-configuration.md
Update the settings object example on the service config page to have the new `services` key (and remove the old `http.`, `https.` and `ssh.` keys).
=> Update settings object example with multiservice config

docs/bird-management/virtual-canaries.md
One of our awesome customers spotted that the `/api/v1/canaryvm/download` API endpoint has an undocumented optional argument `format`. This PR adds the missing arg to our docs:
=> Add `format` argument for `/api/v1/canaryvm/download` endpoint

docs/canarytokens/actions.md
Adds `custom_domain` parameter which specifies the Canarytokens domain to use when creating a Canarytoken.
Also fixed the alphabetical ordering of two items in the wrong place.
Checked changes on the local dev setup and all renders as expected.
=> Add custom_domain field to canarytoken/create endpoint

docs/canarytokens/factory.md
Documentation update to note the new `custom_domain` argument that can be used when creating Canarytokens with a factory.
Checked it renders as expected when deployed locally.
=> Add custom_domain argument to endpoint to create Canarytokens using factory

docs/canarytokens/actions.md, docs/canarytokens/factory.md
Minor change to add missing `required` field for some of the args passed when creating a Canarytoken.
=> Add missing instances of required for Canarytoken create endpoints

docs/canarytokens/factory.md
`expected_referrer` is listed twice in the documentation for `/api/v1/canarytoken/factory/create`
=> Remove duplicate query field: expected_referrer

docs/incidents/incident-objects.md, docs/syslog/rfc5424.md
Some notification objects aren't present in the rfc5424 docs page. Since that data format has its own structure, we need to include samples of each of those objects in this page too.
=> Add missing notification types to rfc5424 docs
